package lk.ijse.computerShop.util;

public enum Routes {
    DASHBOARD,DASHBOARD2,CUSTOMER,ITEM,ORDERS,PLACEORDERS,ORDERDETALIS,SUPPLYER,STOCK,DEATILSORDER,EMPLOYES,SERVISE,ORDERSSUPPLYER,LOGUOT,REPORT,ABOUT
}
